name: Heimdall CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: yarn run lint

  test:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g @quasar/cli
      - run: npm install
      - run: quasar build
      - uses: actions/upload-artifact@v3
        with:
          name: heimdall
          path: dist
